alter table if exists experiences
drop constraint if exists FK1sm1n9ki6d595fbkcsy8mc6f9;
alter table if exists project_technology
drop constraint if exists FK9omsb3aspqa5enyweggvolgtr;
alter table if exists project_technology
drop constraint if exists FKihk0ca5gdtcps1anv6fteywyo;
alter table if exists resume_interest
drop constraint if exists FKbbtdptsyqut9p19ro32m9cbd6;
alter table if exists resume_interest
drop constraint if exists FKtk21lqauoogq1d8r3o661ron8;
alter table if exists resume_language_proficiencies
drop constraint if exists FK7fefp1oguivpxa1cyhl1qjwt4;
alter table if exists resume_language_proficiencies
drop constraint if exists FK8aodlvadbivyarkve4mb54mio;
alter table if exists resume_skill
drop constraint if exists FKhswsfuyai9o2tlmeuap0npa4o;
alter table if exists resume_skill
drop constraint if exists FKowoyk1e94a9bbdikschh5lblj;
alter table if exists skills
drop constraint if exists FKl16l87m9kquuuuecnq1fx5hem;
drop table if exists about_content cascade;
drop table if exists certifications cascade;
drop table if exists companies cascade;
drop table if exists education cascade;
drop table if exists experiences cascade;
drop table if exists interests cascade;
drop table if exists languages_spoken cascade;
drop table if exists project_technology cascade;
drop table if exists projects cascade;
drop table if exists resume_content cascade;
drop table if exists resume_interest cascade;
drop table if exists resume_language_proficiencies cascade;
drop table if exists resume_skill cascade;
drop table if exists skill_categories cascade;
drop table if exists skills cascade;
drop table if exists users cascade;
create table about_content (
                               id bigint not null,
                               title varchar(255),
                               body TEXT,
                               primary key (id)
);
create table certifications (
                                display_order integer,
                                id bigint generated by default as identity,
                                date_issued varchar(255),
                                issuer varchar(255),
                                name varchar(255) not null,
                                verify_url varchar(255),
                                primary key (id)
);
create table companies (
                           id bigint generated by default as identity,
                           logo_url varchar(255),
                           name varchar(255) not null unique,
                           website_url varchar(255),
                           primary key (id)
);
create table education (
                           display_order integer,
                           id bigint generated by default as identity,
                           degree varchar(255) not null,
                           university varchar(255) not null,
                           years varchar(255),
                           details TEXT,
                           primary key (id)
);
create table experiences (
                             display_order integer,
                             company_id bigint not null,
                             id bigint generated by default as identity,
                             job_title varchar(255) not null,
                             location varchar(255),
                             years varchar(255),
                             description TEXT,
                             primary key (id)
);
create table interests (
                           id bigint generated by default as identity,
                           name varchar(255) not null unique,
                           primary key (id)
);
create table languages_spoken (
                                  id bigint generated by default as identity,
                                  name varchar(255) not null unique,
                                  primary key (id)
);
create table project_technology (
                                    project_id bigint not null,
                                    skill_id bigint not null,
                                    primary key (project_id, skill_id)
);
create table projects (
                          display_order integer,
                          id bigint generated by default as identity,
                          image_url varchar(255),
                          live_url varchar(255),
                          repo_url varchar(255),
                          title varchar(255) not null,
                          description TEXT,
                          primary key (id)
);
create table resume_content (
                                id bigint not null,
                                contact_email varchar(255),
                                contact_github_url varchar(255),
                                contact_linkedin_url varchar(255),
                                contact_location varchar(255),
                                contact_name varchar(255),
                                contact_page_title varchar(255),
                                summary TEXT,
                                primary key (id)
);
create table resume_interest (
                                 interest_id bigint not null,
                                 resume_content_id bigint not null,
                                 primary key (interest_id, resume_content_id)
);
create table resume_language_proficiencies (
                                               display_order integer,
                                               id bigint generated by default as identity,
                                               language_id bigint not null,
                                               resume_content_id bigint not null,
                                               proficiency_level varchar(255) not null,
                                               primary key (id)
);
create table resume_skill (
                              resume_content_id bigint not null,
                              skill_id bigint not null,
                              primary key (resume_content_id, skill_id)
);
create table skill_categories (
                                  display_order integer,
                                  id bigint generated by default as identity,
                                  name varchar(255) not null unique,
                                  primary key (id)
);
create table skills (
                        category_id bigint,
                        id bigint generated by default as identity,
                        icon_identifier varchar(255),
                        name varchar(255) not null unique,
                        primary key (id)
);
create table users (
                       enabled boolean not null,
                       id bigint generated by default as identity,
                       password varchar(255) not null,
                       roles varchar(255) not null,
                       username varchar(255) not null unique,
                       primary key (id)
);
alter table if exists experiences
    add constraint FK1sm1n9ki6d595fbkcsy8mc6f9
    foreign key (company_id)
    references companies;
alter table if exists project_technology
    add constraint FK9omsb3aspqa5enyweggvolgtr
    foreign key (skill_id)
    references skills;
alter table if exists project_technology
    add constraint FKihk0ca5gdtcps1anv6fteywyo
    foreign key (project_id)
    references projects;
alter table if exists resume_interest
    add constraint FKbbtdptsyqut9p19ro32m9cbd6
    foreign key (interest_id)
    references interests;
alter table if exists resume_interest
    add constraint FKtk21lqauoogq1d8r3o661ron8
    foreign key (resume_content_id)
    references resume_content;
alter table if exists resume_language_proficiencies
    add constraint FK7fefp1oguivpxa1cyhl1qjwt4
    foreign key (language_id)
    references languages_spoken;
alter table if exists resume_language_proficiencies
    add constraint FK8aodlvadbivyarkve4mb54mio
    foreign key (resume_content_id)
    references resume_content;
alter table if exists resume_skill
    add constraint FKhswsfuyai9o2tlmeuap0npa4o
    foreign key (skill_id)
    references skills;
alter table if exists resume_skill
    add constraint FKowoyk1e94a9bbdikschh5lblj
    foreign key (resume_content_id)
    references resume_content;
alter table if exists skills
    add constraint FKl16l87m9kquuuuecnq1fx5hem
    foreign key (category_id)
    references skill_categories;
